// 
export const avatarAssets = {

  // 0~35, url: /avatar/skin/skinXX.png
  'skin00': '/avatar/skin/skin00.png',
  'skin01': '/avatar/skin/skin01.png',
  'skin02': '/avatar/skin/skin02.png',
  'skin03': '/avatar/skin/skin03.png',
  'skin04': '/avatar/skin/skin04.png',
  'skin05': '/avatar/skin/skin05.png',
  'skin06': '/avatar/skin/skin06.png',
  'skin07': '/avatar/skin/skin07.png',
  'skin08': '/avatar/skin/skin08.png',
  'skin09': '/avatar/skin/skin09.png',
  'skin10': '/avatar/skin/skin10.png',
  'skin11': '/avatar/skin/skin11.png',
  'skin12': '/avatar/skin/skin12.png',
  'skin13': '/avatar/skin/skin13.png',
  'skin14': '/avatar/skin/skin14.png',
  'skin15': '/avatar/skin/skin15.png',
  'skin16': '/avatar/skin/skin16.png',
  'skin17': '/avatar/skin/skin17.png',
  'skin18': '/avatar/skin/skin18.png',
  'skin19': '/avatar/skin/skin19.png',
  'skin20': '/avatar/skin/skin20.png',
  'skin21': '/avatar/skin/skin21.png',
  'skin22': '/avatar/skin/skin22.png',
  'skin23': '/avatar/skin/skin23.png',
  'skin24': '/avatar/skin/skin24.png',
  'skin25': '/avatar/skin/skin25.png',
  'skin26': '/avatar/skin/skin26.png',
  'skin27': '/avatar/skin/skin27.png',
  'skin28': '/avatar/skin/skin28.png',
  'skin29': '/avatar/skin/skin29.png',
  'skin30': '/avatar/skin/skin30.png',
  'skin31': '/avatar/skin/skin31.png',
  'skin32': '/avatar/skin/skin32.png',
  'skin33': '/avatar/skin/skin33.png',
  'skin34': '/avatar/skin/skin34.png',
  'skin35': '/avatar/skin/skin35.png',
  // 0~30, url: /avatar/top/topXX.png
  'top00': '/avatar/top/top00.png',
  'top01': '/avatar/top/top01.png',
  'top02': '/avatar/top/top02.png',
  'top03': '/avatar/top/top03.png',
  'top04': '/avatar/top/top04.png',
  'top05': '/avatar/top/top05.png',
  'top06': '/avatar/top/top06.png',
  'top07': '/avatar/top/top07.png',
  'top08': '/avatar/top/top08.png',
  'top09': '/avatar/top/top09.png',
  'top10': '/avatar/top/top10.png',
  'top11': '/avatar/top/top11.png',
  'top12': '/avatar/top/top12.png',
  'top13': '/avatar/top/top13.png',
  'top14': '/avatar/top/top14.png',
  'top15': '/avatar/top/top15.png',
  'top16': '/avatar/top/top16.png',
  'top17': '/avatar/top/top17.png',
  'top18': '/avatar/top/top18.png',
  'top19': '/avatar/top/top19.png',
  'top20': '/avatar/top/top20.png',
  'top21': '/avatar/top/top21.png',
  'top22': '/avatar/top/top22.png',
  'top23': '/avatar/top/top23.png',
  'top24': '/avatar/top/top24.png',
  'top25': '/avatar/top/top25.png',
  'top26': '/avatar/top/top26.png',
  'top27': '/avatar/top/top27.png',
  'top28': '/avatar/top/top28.png',
  'top29': '/avatar/top/top29.png',
  'top30': '/avatar/top/top30.png',
}

export const bgAssets = {
  'home-mobile': '/bg/home-mobile.png',
  'home-desktop': '/bg/home-desktop.png',
}