// 
export const avatarAssets = {

  // 0~35, url: /images/avatar/skin/skinXX.png
  'skin00': '/images/avatar/skin/skin00.png',
  'skin01': '/images/avatar/skin/skin01.png',
  'skin02': '/images/avatar/skin/skin02.png',
  'skin03': '/images/avatar/skin/skin03.png',
  'skin04': '/images/avatar/skin/skin04.png',
  'skin05': '/images/avatar/skin/skin05.png',
  'skin06': '/images/avatar/skin/skin06.png',
  'skin07': '/images/avatar/skin/skin07.png',
  'skin08': '/images/avatar/skin/skin08.png',
  'skin09': '/images/avatar/skin/skin09.png',
  'skin10': '/images/avatar/skin/skin10.png',
  'skin11': '/images/avatar/skin/skin11.png',
  'skin12': '/images/avatar/skin/skin12.png',
  'skin13': '/images/avatar/skin/skin13.png',
  'skin14': '/images/avatar/skin/skin14.png',
  'skin15': '/images/avatar/skin/skin15.png',
  'skin16': '/images/avatar/skin/skin16.png',
  'skin17': '/images/avatar/skin/skin17.png',
  'skin18': '/images/avatar/skin/skin18.png',
  'skin19': '/images/avatar/skin/skin19.png',
  'skin20': '/images/avatar/skin/skin20.png',
  'skin21': '/images/avatar/skin/skin21.png',
  'skin22': '/images/avatar/skin/skin22.png',
  'skin23': '/images/avatar/skin/skin23.png',
  'skin24': '/images/avatar/skin/skin24.png',
  'skin25': '/images/avatar/skin/skin25.png',
  'skin26': '/images/avatar/skin/skin26.png',
  'skin27': '/images/avatar/skin/skin27.png',
  'skin28': '/images/avatar/skin/skin28.png',
  'skin29': '/images/avatar/skin/skin29.png',
  'skin30': '/images/avatar/skin/skin30.png',
  'skin31': '/images/avatar/skin/skin31.png',
  'skin32': '/images/avatar/skin/skin32.png',
  'skin33': '/images/avatar/skin/skin33.png',
  'skin34': '/images/avatar/skin/skin34.png',
  'skin35': '/images/avatar/skin/skin35.png',
  // 0~30, url: /images/avatar/accessory/accessoryXX.png
  'accessory00': '/images/avatar/accessory/accessory00.png',
  'accessory01': '/images/avatar/accessory/accessory01.png',
  'accessory02': '/images/avatar/accessory/accessory02.png',
  'accessory03': '/images/avatar/accessory/accessory03.png',
  'accessory04': '/images/avatar/accessory/accessory04.png',
  'accessory05': '/images/avatar/accessory/accessory05.png',
  'accessory06': '/images/avatar/accessory/accessory06.png',
  'accessory07': '/images/avatar/accessory/accessory07.png',
  'accessory08': '/images/avatar/accessory/accessory08.png',
  'accessory09': '/images/avatar/accessory/accessory09.png',
  'accessory10': '/images/avatar/accessory/accessory10.png',
  'accessory11': '/images/avatar/accessory/accessory11.png',
  'accessory12': '/images/avatar/accessory/accessory12.png',
  'accessory13': '/images/avatar/accessory/accessory13.png',
  'accessory14': '/images/avatar/accessory/accessory14.png',
  'accessory15': '/images/avatar/accessory/accessory15.png',
  'accessory16': '/images/avatar/accessory/accessory16.png',
  'accessory17': '/images/avatar/accessory/accessory17.png',
  'accessory18': '/images/avatar/accessory/accessory18.png',
  'accessory19': '/images/avatar/accessory/accessory19.png',
  'accessory20': '/images/avatar/accessory/accessory20.png',
  'accessory21': '/images/avatar/accessory/accessory21.png',
  'accessory22': '/images/avatar/accessory/accessory22.png',
  'accessory23': '/images/avatar/accessory/accessory23.png',
  'accessory24': '/images/avatar/accessory/accessory24.png',
  'accessory25': '/images/avatar/accessory/accessory25.png',
  'accessory26': '/images/avatar/accessory/accessory26.png',
  'accessory27': '/images/avatar/accessory/accessory27.png',
  'accessory28': '/images/avatar/accessory/accessory28.png',
  'accessory29': '/images/avatar/accessory/accessory29.png',
  'accessory30': '/images/avatar/accessory/accessory30.png',
}

export const bgAssets = {
  'home-mobile': '/images/bg/home-mobile.png',
  'home-desktop': '/images/bg/home-desktop.png',
}

export const soundEffectsAssets = {
  'gameover': '/sounds/effect/gameover.mp3',
  'ddok!': '/sounds/effect/ddok!.mp3',
  'ddok': '/sounds/effect/ddok.mp3',
  'ddududu': '/sounds/effect/ddududu.mp3',
  'ddurut': '/sounds/effect/ddurut.mp3',
  'ddik': '/sounds/effect/ddik.mp3',
  'dding': '/sounds/effect/dding.mp3',
  'bubble': '/sounds/effect/bubble.mp3',
  'boblebogglebobleboggle': '/sounds/effect/boblebogglebobleboggle.mp3',
  'bbap': '/sounds/effect/bbap.mp3',
  'word': '/sounds/effect/word.mp3',
  'chalbakchalbak': '/sounds/effect/chalbakchalbak.mp3',
  'chung': '/sounds/effect/chung.mp3',
  'chulugrruk': '/sounds/effect/chulugrruk.mp3',
  'taek': '/sounds/effect/taek.mp3',
  'toong': '/sounds/effect/toong.mp3',
  'pyap!': '/sounds/effect/pyap!.mp3',
  'pubobob': '/sounds/effect/pubobob.mp3',
  'pororororororog': '/sounds/effect/pororororororog.mp3',
  'hwiwoong': '/sounds/effect/hwiwoong.mp3',
  'hwiip': '/sounds/effect/hwiip.mp3',
}

export const musicAssets = {
  'timeattack': '/sounds/music/timeattack.mp3',
  'waiting': '/sounds/music/waiting.mp3',
  'lobby': '/sounds/music/lobby.mp3',
  'citymafia': '/sounds/music/citymafia.mp3',
  'kidsgame': '/sounds/music/kidsgame.mp3',
}