// 
export const avatarAssets = {

  // 0~35, url: /images/avatar/skin/skinXX.png
  'skin00': '/images/avatar/skin/skin00.png',
  'skin01': '/images/avatar/skin/skin01.png',
  'skin02': '/images/avatar/skin/skin02.png',
  'skin03': '/images/avatar/skin/skin03.png',
  'skin04': '/images/avatar/skin/skin04.png',
  'skin05': '/images/avatar/skin/skin05.png',
  'skin06': '/images/avatar/skin/skin06.png',
  'skin07': '/images/avatar/skin/skin07.png',
  'skin08': '/images/avatar/skin/skin08.png',
  'skin09': '/images/avatar/skin/skin09.png',
  'skin10': '/images/avatar/skin/skin10.png',
  'skin11': '/images/avatar/skin/skin11.png',
  'skin12': '/images/avatar/skin/skin12.png',
  'skin13': '/images/avatar/skin/skin13.png',
  'skin14': '/images/avatar/skin/skin14.png',
  'skin15': '/images/avatar/skin/skin15.png',
  'skin16': '/images/avatar/skin/skin16.png',
  'skin17': '/images/avatar/skin/skin17.png',
  'skin18': '/images/avatar/skin/skin18.png',
  'skin19': '/images/avatar/skin/skin19.png',
  'skin20': '/images/avatar/skin/skin20.png',
  'skin21': '/images/avatar/skin/skin21.png',
  'skin22': '/images/avatar/skin/skin22.png',
  'skin23': '/images/avatar/skin/skin23.png',
  'skin24': '/images/avatar/skin/skin24.png',
  'skin25': '/images/avatar/skin/skin25.png',
  'skin26': '/images/avatar/skin/skin26.png',
  'skin27': '/images/avatar/skin/skin27.png',
  'skin28': '/images/avatar/skin/skin28.png',
  'skin29': '/images/avatar/skin/skin29.png',
  'skin30': '/images/avatar/skin/skin30.png',
  'skin31': '/images/avatar/skin/skin31.png',
  'skin32': '/images/avatar/skin/skin32.png',
  'skin33': '/images/avatar/skin/skin33.png',
  'skin34': '/images/avatar/skin/skin34.png',
  'skin35': '/images/avatar/skin/skin35.png',
  // 0~30, url: /images/avatar/top/topXX.png
  'top00': '/images/avatar/top/top00.png',
  'top01': '/images/avatar/top/top01.png',
  'top02': '/images/avatar/top/top02.png',
  'top03': '/images/avatar/top/top03.png',
  'top04': '/images/avatar/top/top04.png',
  'top05': '/images/avatar/top/top05.png',
  'top06': '/images/avatar/top/top06.png',
  'top07': '/images/avatar/top/top07.png',
  'top08': '/images/avatar/top/top08.png',
  'top09': '/images/avatar/top/top09.png',
  'top10': '/images/avatar/top/top10.png',
  'top11': '/images/avatar/top/top11.png',
  'top12': '/images/avatar/top/top12.png',
  'top13': '/images/avatar/top/top13.png',
  'top14': '/images/avatar/top/top14.png',
  'top15': '/images/avatar/top/top15.png',
  'top16': '/images/avatar/top/top16.png',
  'top17': '/images/avatar/top/top17.png',
  'top18': '/images/avatar/top/top18.png',
  'top19': '/images/avatar/top/top19.png',
  'top20': '/images/avatar/top/top20.png',
  'top21': '/images/avatar/top/top21.png',
  'top22': '/images/avatar/top/top22.png',
  'top23': '/images/avatar/top/top23.png',
  'top24': '/images/avatar/top/top24.png',
  'top25': '/images/avatar/top/top25.png',
  'top26': '/images/avatar/top/top26.png',
  'top27': '/images/avatar/top/top27.png',
  'top28': '/images/avatar/top/top28.png',
  'top29': '/images/avatar/top/top29.png',
  'top30': '/images/avatar/top/top30.png',
}

export const bgAssets = {
  'home-mobile': '/images/bg/home-mobile.png',
  'home-desktop': '/images/bg/home-desktop.png',
}

export const soundEffectsAssets = {
  'gameover': '/sounds/effect/gameover.mp3',
  'ddok!': '/sounds/effect/ddok!.mp3',
  'ddok': '/sounds/effect/ddok.mp3',
  'ddududu': '/sounds/effect/ddududu.mp3',
  'ddurut': '/sounds/effect/ddurut.mp3',
  'ddik': '/sounds/effect/ddik.mp3',
  'dding': '/sounds/effect/dding.mp3',
  'bubble': '/sounds/effect/bubble.mp3',
  'boblebogglebobleboggle': '/sounds/effect/boblebogglebobleboggle.mp3',
  'bbap': '/sounds/effect/bbap.mp3',
  'word': '/sounds/effect/word.mp3',
  'chalbakchalbak': '/sounds/effect/chalbakchalbak.mp3',
  'chung': '/sounds/effect/chung.mp3',
  'chulugrruk': '/sounds/effect/chulugrruk.mp3',
  'taek': '/sounds/effect/taek.mp3',
  'toong': '/sounds/effect/toong.mp3',
  'pyap!': '/sounds/effect/pyap!.mp3',
  'pubobob': '/sounds/effect/pubobob.mp3',
  'pororororororog': '/sounds/effect/pororororororog.mp3',
  'hwiwoong': '/sounds/effect/hwiwoong.mp3',
  'hwiip': '/sounds/effect/hwiip.mp3',
}

export const musicAssets = {
  'timeattack': '/sounds/music/timeattack.mp3',
  'waiting': '/sounds/music/waiting.mp3',
  'lobby': '/sounds/music/lobby.mp3',
  'citymafia': '/sounds/music/citymafia.mp3',
  'kidsgame': '/sounds/music/kidsgame.mp3',
}